task:
  container:
    image: python:latest
  python_modules_populate_script: make deps
  matrix:
    - name: Unit Tests
      script: make test-and-report
      always:
        unittest_results_artifacts:
          path: ./*.xml
          format: junit
          type: text/xml
    - name: Static Analysis
      script: make lint

